/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBookTransactionsGetCollection200HydraSearchHydraMappingItemProperty } from './apiBookTransactionsGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiBookTransactionsGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiBookTransactionsGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
};
