/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBooksGetCollection200HydraSearchHydraMappingItemProperty } from './apiBooksGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiBooksGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiBooksGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
};
