/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookJsonld } from './bookJsonld';
import type { ApiBooksGetCollection200HydraView } from './apiBooksGetCollection200HydraView';
import type { ApiBooksGetCollection200HydraSearch } from './apiBooksGetCollection200HydraSearch';

export type ApiBooksGetCollection200 = {
  'hydra:member': BookJsonld[];
  /** @minimum 0 */
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiBooksGetCollection200HydraView;
  'hydra:search'?: ApiBooksGetCollection200HydraSearch;
};
