/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBookTransactionsGetCollection200HydraSearchHydraMappingItem } from './apiBookTransactionsGetCollection200HydraSearchHydraMappingItem';

export type ApiBookTransactionsGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
  'hydra:mapping'?: ApiBookTransactionsGetCollection200HydraSearchHydraMappingItem[];
};
