/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookTransactionJsonld } from './bookTransactionJsonld';
import type { ApiBookTransactionsGetCollection200HydraView } from './apiBookTransactionsGetCollection200HydraView';
import type { ApiBookTransactionsGetCollection200HydraSearch } from './apiBookTransactionsGetCollection200HydraSearch';

export type ApiBookTransactionsGetCollection200 = {
  'hydra:member': BookTransactionJsonld[];
  /** @minimum 0 */
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiBookTransactionsGetCollection200HydraView;
  'hydra:search'?: ApiBookTransactionsGetCollection200HydraSearch;
};
