/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBooksGetCollection200HydraSearchHydraMappingItem } from './apiBooksGetCollection200HydraSearchHydraMappingItem';

export type ApiBooksGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
  'hydra:mapping'?: ApiBooksGetCollection200HydraSearchHydraMappingItem[];
};
