/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiFavoriteBooksGetCollection200HydraSearchHydraMappingItem } from './apiFavoriteBooksGetCollection200HydraSearchHydraMappingItem';

export type ApiFavoriteBooksGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
  'hydra:mapping'?: ApiFavoriteBooksGetCollection200HydraSearchHydraMappingItem[];
};
