/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBookJsonld } from './favoriteBookJsonld';
import type { ApiFavoriteBooksGetCollection200HydraView } from './apiFavoriteBooksGetCollection200HydraView';
import type { ApiFavoriteBooksGetCollection200HydraSearch } from './apiFavoriteBooksGetCollection200HydraSearch';

export type ApiFavoriteBooksGetCollection200 = {
  'hydra:member': FavoriteBookJsonld[];
  /** @minimum 0 */
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiFavoriteBooksGetCollection200HydraView;
  'hydra:search'?: ApiFavoriteBooksGetCollection200HydraSearch;
};
