/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiFavoriteBooksGetCollection200HydraSearchHydraMappingItemProperty } from './apiFavoriteBooksGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiFavoriteBooksGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiFavoriteBooksGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
};
