/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiMessagesGetCollection200HydraSearchHydraMappingItem } from './apiMessagesGetCollection200HydraSearchHydraMappingItem';

export type ApiMessagesGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
  'hydra:mapping'?: ApiMessagesGetCollection200HydraSearchHydraMappingItem[];
};
