/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ApiMessagesGetCollectionParams = {
/**
 * The collection page number
 */
page?: number;
'sender.id'?: number;
'sender.id[]'?: number[];
'receiver.id'?: number;
'receiver.id[]'?: number[];
'fromBook.id'?: number;
'fromBook.id[]'?: number[];
};
