/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MessageJsonld } from './messageJsonld';
import type { ApiMessagesGetCollection200HydraView } from './apiMessagesGetCollection200HydraView';
import type { ApiMessagesGetCollection200HydraSearch } from './apiMessagesGetCollection200HydraSearch';

export type ApiMessagesGetCollection200 = {
  'hydra:member': MessageJsonld[];
  /** @minimum 0 */
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiMessagesGetCollection200HydraView;
  'hydra:search'?: ApiMessagesGetCollection200HydraSearch;
};
