/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiMessagesGetCollection200HydraSearchHydraMappingItemProperty } from './apiMessagesGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiMessagesGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiMessagesGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
};
