/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonld } from './userJsonld';
import type { ApiUsersGetCollection200HydraView } from './apiUsersGetCollection200HydraView';
import type { ApiUsersGetCollection200HydraSearch } from './apiUsersGetCollection200HydraSearch';

export type ApiUsersGetCollection200 = {
  'hydra:member': UserJsonld[];
  /** @minimum 0 */
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiUsersGetCollection200HydraView;
  'hydra:search'?: ApiUsersGetCollection200HydraSearch;
};
