/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiUsersGetCollection200HydraSearchHydraMappingItem } from './apiUsersGetCollection200HydraSearchHydraMappingItem';

export type ApiUsersGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
  'hydra:mapping'?: ApiUsersGetCollection200HydraSearchHydraMappingItem[];
};
