/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiUsersGetCollection200HydraSearchHydraMappingItemProperty } from './apiUsersGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiUsersGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiUsersGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
};
