/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookTransactionJsonldTransactionType = typeof BookTransactionJsonldTransactionType[keyof typeof BookTransactionJsonldTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookTransactionJsonldTransactionType = {
  purchase: 'purchase',
  sale: 'sale',
  swap: 'swap',
} as const;
