/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookJsonldContext } from './bookJsonldContext';
import type { BookJsonldStatus } from './bookJsonldStatus';
import type { BookJsonldInterchangeable } from './bookJsonldInterchangeable';

export interface BookJsonld {
  readonly '@context'?: BookJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  name?: string;
  author?: string;
  price?: number;
  category?: number;
  isInterchangeable?: boolean;
  createdAt?: string;
  ubicatedIn?: number;
  description?: string;
  status?: BookJsonldStatus;
  imageBook?: string;
  owner?: string;
  favoriteBooks?: string[];
  bookTransactions?: string[];
  messages?: string[];
  readonly interchangeable?: BookJsonldInterchangeable;
}
