/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookJsonldContextOneOfHydra = typeof BookJsonldContextOneOfHydra[keyof typeof BookJsonldContextOneOfHydra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const;
