/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookStatus } from './bookStatus';
import type { BookInterchangeable } from './bookInterchangeable';

export interface Book {
  readonly id?: number;
  name?: string;
  author?: string;
  price?: number;
  category?: number;
  isInterchangeable?: boolean;
  createdAt?: string;
  ubicatedIn?: number;
  description?: string;
  status?: BookStatus;
  imageBook?: string;
  owner?: string;
  favoriteBooks?: string[];
  bookTransactions?: string[];
  messages?: string[];
  readonly interchangeable?: BookInterchangeable;
}
