/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookTransactionTransactionType = typeof BookTransactionTransactionType[keyof typeof BookTransactionTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookTransactionTransactionType = {
  Purchase: 'Purchase',
  Sale: 'Sale',
  Swap: 'Swap',
} as const;
