/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookTransactionJsonldContext } from './bookTransactionJsonldContext';
import type { BookTransactionJsonldTransactionType } from './bookTransactionJsonldTransactionType';
import type { BookTransactionJsonldStatusTransaction } from './bookTransactionJsonldStatusTransaction';
import type { BookTransactionJsonldBuyer } from './bookTransactionJsonldBuyer';

export interface BookTransactionJsonld {
  readonly '@context'?: BookTransactionJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  transactionType?: BookTransactionJsonldTransactionType;
  statusTransaction?: BookTransactionJsonldStatusTransaction;
  createdAt?: string;
  buyer?: BookTransactionJsonldBuyer;
  seller?: string;
  book?: string;
}
