/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookTransactionStatusTransaction = typeof BookTransactionStatusTransaction[keyof typeof BookTransactionStatusTransaction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookTransactionStatusTransaction = {
  Pending: 'Pending',
  Completed: 'Completed',
  Canceled: 'Canceled',
} as const;
