/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookInterchangeable } from './bookInterchangeable';

export interface Book {
  readonly id?: number;
  name?: string;
  author?: string;
  price?: number;
  category?: number;
  isInterchangeable?: boolean;
  createdAt?: string;
  ubicatedIn?: number;
  description?: string;
  ownerId?: number;
  status?: string;
  imageBook?: string;
  readonly interchangeable?: BookInterchangeable;
}
