/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookTransactionJsonldStatusTransaction = typeof BookTransactionJsonldStatusTransaction[keyof typeof BookTransactionJsonldStatusTransaction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookTransactionJsonldStatusTransaction = {
  pending: 'pending',
  completed: 'completed',
  canceled: 'canceled',
} as const;
