/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type BookStatus = typeof BookStatus[keyof typeof BookStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookStatus = {
  available: 'available',
  sold: 'sold',
  swap: 'swap',
} as const;
