/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookTransactionTransactionType } from './bookTransactionTransactionType';
import type { BookTransactionStatusTransaction } from './bookTransactionStatusTransaction';
import type { BookTransactionBuyer } from './bookTransactionBuyer';

export interface BookTransaction {
  readonly id?: number;
  transactionType?: BookTransactionTransactionType;
  statusTransaction?: BookTransactionStatusTransaction;
  createdAt?: string;
  buyer?: BookTransactionBuyer;
  seller?: string;
  book?: string;
}
