/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBookJsonldContext } from './favoriteBookJsonldContext';
import type { FavoriteBookJsonldBook } from './favoriteBookJsonldBook';

export interface FavoriteBookJsonld {
  readonly '@context'?: FavoriteBookJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  createdAt?: string;
  user?: string;
  book?: FavoriteBookJsonldBook;
}
