/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBookJsonldContextOneOfHydra } from './favoriteBookJsonldContextOneOfHydra';

export type FavoriteBookJsonldContextOneOf = {
  '@vocab': string;
  hydra: FavoriteBookJsonldContextOneOfHydra;
  [key: string]: unknown;
 };
