/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBookBook } from './favoriteBookBook';

export interface FavoriteBook {
  readonly id?: number;
  createdAt?: string;
  user?: string;
  book?: FavoriteBookBook;
}
