/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MessageJsonldContext } from './messageJsonldContext';

export interface MessageJsonld {
  readonly '@context'?: MessageJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  text?: string;
  createdAt?: string;
  fromBook?: string;
  sender?: string;
  receiver?: string;
}
