/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MessageJsonldContextOneOf } from './messageJsonldContextOneOf';

export type MessageJsonldContext = string | MessageJsonldContextOneOf;
