/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export interface Message {
  readonly id?: number;
  text?: string;
  createdAt?: string;
  fromBook?: string;
  sender?: string;
  receiver?: string;
}
