/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonldUserReadContextOneOf } from './userJsonldUserReadContextOneOf';

export type UserJsonldUserReadContext = string | UserJsonldUserReadContextOneOf;
