/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  readonly id?: number;
  username?: string;
  email?: string;
  name?: string;
  surname?: string;
  password?: string;
  createdAt?: string;
  lastLogin?: string;
  readonly roles?: readonly string[];
  readonly userIdentifier?: string;
}
