/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonldContext } from './userJsonldContext';

export interface UserJsonld {
  readonly '@context'?: UserJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  username?: string;
  email?: string;
  name?: string;
  surname?: string;
  password?: string;
  createdAt?: string;
  lastLogin?: string;
  readonly roles?: readonly string[];
  readonly userIdentifier?: string;
}
