/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonldContextOneOfHydra } from './userJsonldContextOneOfHydra';

export type UserJsonldContextOneOf = {
  '@vocab': string;
  hydra: UserJsonldContextOneOfHydra;
  [key: string]: unknown;
 };
